export const SET_PAYLOAD = 'SET_PAYLOAD';
export const SET_FILE = 'SET_FILE';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_PREVIEW_VISBILITY = 'SET_PREVIEW_VISBILITY';
export const SET_IS_UPLOAD_RUNNING_STATE = 'SET_IS_UPLOAD_RUNNING_STATE';
export const RESET_STORE = 'RESET_STORE';
